rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  — job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      — targets: [https://skillfactory.ru]

  — job_name: lms
    scrape_interval: 5s
    static_configs:
      — targets: [lms.skillfactory.ru]


    relabel_configs:
      — source_labels: [__address__]
        target_label: __param_target
      — source_labels: [__param_target]
        target_label: instance
      — target_label: __address__
        replacement: blackbox-exporter:9115

  — job_name: node
    scrape_interval: 5s
    static_configs:
      — targets: ['node-exporter:9100']
